// src/enums/ApiErrorEnum.ts
export const ApiErrorEnum = {
  // General API Errors
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  
  // Authentication & Authorization Errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  
  // Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
  INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
  INVALID_FIELD_VALUE: 'INVALID_FIELD_VALUE',
  
  // Client/Profile Related Errors
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  CLIENT_ALREADY_EXISTS: 'CLIENT_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PROFILE_UPDATE_FAILED: 'PROFILE_UPDATE_FAILED',
  PROFILE_CREATE_FAILED: 'PROFILE_CREATE_FAILED',
  
  // Airtable Specific Errors
  AIRTABLE_RATE_LIMIT: 'AIRTABLE_RATE_LIMIT',
  AIRTABLE_QUOTA_EXCEEDED: 'AIRTABLE_QUOTA_EXCEEDED',
  AIRTABLE_INVALID_REQUEST: 'AIRTABLE_INVALID_REQUEST',
  AIRTABLE_RECORD_NOT_FOUND: 'AIRTABLE_RECORD_NOT_FOUND',
  AIRTABLE_FIELD_MISSING: 'AIRTABLE_FIELD_MISSING',
  
  // Server Errors
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  BAD_GATEWAY: 'BAD_GATEWAY',
  
  // Business Logic Errors
  DUPLICATE_OPERATION: 'DUPLICATE_OPERATION',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS'
} as const;

export type ApiErrorEnum = typeof ApiErrorEnum[keyof typeof ApiErrorEnum];